### ISSUE TITLE
Add dependabot for GitHub Actions

### ISSUE THREAD

**Issue by Alkarex** [alexandrainst/alexandra-ml-template#16]
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

Example:

```yml
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
```
